### ISSUE TITLE
Check annotation workflow

### ISSUE THREAD

**Issue by lwieneke** [C2DH/histograph#12]
When annotating a person in the text I can associate an entity, but this entity does not show up in the people mentioned section on top once I complete an annotation. 
Imho it should do so, could you check if it actually should work like this or if something goes wrong?

**Comment by theorm** [comment]
Select-and-annotate indeed works, however it uses a different mechanism than ingestion time annotation. The entities are not really linked to resources in a usual way. This has been rectified in a recent pull request by allowing to select a part of text, search related entities and link them to the document but without a context position in the text. Detecting selected position is not possible without refactoring of the part of the UI responsible for it.

**Comment by theorm** [comment]
Addressed in https://github.com/C2DH/histograph/pull/50
