### ISSUE TITLE
"Zoom to resource" in topic modelling view

### ISSUE THREAD

**Issue by theorm** [C2DH/histograph#2]
Add a "zoom to resource" button to the topic modelling view. Clicking the button will make the topic modelling chart zoom in until the resource level (where one bar is equal to one resource). We can use the centre of the graph as the zoom in point.

![Screen Shot 2019-07-17 at 1 05 56 pm](https://user-images.githubusercontent.com/89853/61371328-c8437100-a894-11e9-9221-2ae293db7ce9.png)

**Comment by lwieneke** [comment]
Prio 2

For now: we need to have user feedback on whether or not this is actually useful.

**Comment by theorm** [comment]
I had already done it before you commented @lwieneke 🤓
