### ISSUE TITLE
Topic centric view of resources

### ISSUE THREAD

**Issue by theorm** [C2DH/histograph#25]
We want to have a view where we could explore resources belonging to a particular topic. It would have the topic details in a panel on the left (similar to "explore person/location entity" view). The right part would contain a list of resources. 

The resources can be additionally filtered by:
 * start/end date of the resource
 * keyword (from full text search)

The resources can be sorted by:
 * date
 * topic score

We probably need a way to define "presence" of a topic in a resource. Depending on the topic score calculation method it may not be enough to assume that a topic is present if score is greater than 0. We may need to add a threshold slider to the view. Moving the slider would change the cutoff threshold and return resources with scores above the threshold.

**Comment by lwieneke** [comment]
I'd add the "Related to" feature where resources can be filtered by person mentions in the mix as well. It might not be that relevant for the corpus at hand, as the data quality of the entities is not that high, but still useful in future applications.
Hence I'd suggest to add it as a "very nice to have" but just to mention it so we don't forget about it.

+1 for the cut-off slider

**Comment by theorm** [comment]
Implemented in https://github.com/C2DH/histograph/pull/31
