### ISSUE TITLE
Year based bucket view

### ISSUE THREAD

**Issue by lwieneke** [C2DH/histograph#27]
As time turned out to be a very important concept in history Eva mentioned in a previous discussion the idea to have a view that associates the buckets not with an equal number of pages but with years instead (bucket one = 1853, bucket 2: 1854 etc.).

I understand that this could be a helpful and meaningful view, but it might lead to some challenges and could create quite some issues down the line depending on the implementation.

First of all, as the number of pages per year changes, the number of resources per bucket differs. Right now I'm not sure if this creates a problem, but do you think this would cause trouble down the line? 

For the implementation we could think about two options:

- either by defining this annual view as the maximum zoom and setting the amount of buckets and the limits for each bucket as static values or
- by enabling users to define the number of buckets and other criteria (e.g. date) in the interface.

Unless there is a very easy solution at hand, we can keep this as an "idea" rather than a new feature request.

**Comment by theorm** [comment]
Implemented
