### ISSUE TITLE
Highlight selected bucket on topic modelling chart

### ISSUE THREAD

**Issue by theorm** [C2DH/histograph#4]
Permanently highlight selected bucket after clicking on it on the topic modelling chart to load resources. The selected bucket ID should be updated in the URL of the page to be able to navigate between pages and create deep links.
![Screen Shot 2019-07-17 at 1 25 58 pm](https://user-images.githubusercontent.com/89853/61372264-f5911e80-a896-11e9-847c-b83abf00035b.png)

**Comment by lwieneke** [comment]
Prio 1

Eases the navigation within the corpus and by adding the marker to the URL would help to use the "back" button in the browser

**Comment by theorm** [comment]
Implemented.
