### ISSUE TITLE
Add topic view for topics in Topic Modelling

### ISSUE THREAD

**Issue by theorm** [C2DH/histograph#6]
Clicking on the topic label on the topic modelling chart we should see a context side bar which would allow us to edit the label and see the topic context words.

**Comment by lwieneke** [comment]
Prio 1

The ability to define names will be integral to better understand the results of the topic modeling, seeing the underlying terms will help to evaluate the topic

**Comment by theorm** [comment]
Done https://github.com/C2DH/histograph/pull/16
