### ISSUE TITLE
Explore multiple aspects in topic modelling view

### ISSUE THREAD

**Issue by theorm** [C2DH/histograph#8]
At the moment we support only one aspect on the topic modelling chart (in case of the BJP corpus this is the "persons" count). We want to be able to add more than one aspect and do this through the UI. Aspect filter in this case should be moved to the particular aspect section.
![asdf123asdf](https://user-images.githubusercontent.com/89853/61373065-16f30a00-a899-11e9-8433-940912680929.png)

**Comment by lwieneke** [comment]
Prio 1

For me, the first candidate for this feature would be the full-text search feature. If it makes life easier, we could also start working with a hard-coded box including a search field underneath the persons box.

**Comment by theorm** [comment]
Implements https://github.com/C2DH/histograph/pull/18
