### ISSUE TITLE
Add numbers and "max context" to the "Persons" aspect view

### ISSUE THREAD

**Issue by theorm** [C2DH/histograph#9]
At the moment we can see the number of persons in a bucket in relation to other buckets but we cannot see the actual number of "persons" in a bucket. We should display the number of persons at every bar. We should also display the maxium number of persons in the bucket before filtering if a filter is applied which can be done by rendering a faded out bar behind the main bar in every bucket.

**Comment by lwieneke** [comment]
Instead of the number for each bar, we could also add a scale on the y axis. That could help to reduce the visual clutter.

**Comment by theorm** [comment]
Implemented in https://github.com/C2DH/histograph/pull/18
